- name: attach storage
  os_server_volume:
    state: present
    server: "{{ inventory_hostname }}"
    volume: "{{ inventory_hostname }}-{{ openstack_storage_name }}"
    device: "{{ openstack_storage_device }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    region_name: "{{ openstack_region }}"
    availability_zone: "{{ openstack_availability_zone }}"
