- name: attach floating IP
  os_floating_ip:
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    server: "{{ inventory_hostname }}"
    state: present
    reuse: yes
    wait: true
    network: "{{ openstack_fip_network }}"
    timeout: "{{ openstack_fip_timeout }}"
