- name: create storage
  os_volume:
    state: present
    size: "{{ openstack_storage_size }}"
    display_name: "{{ inventory_hostname }}-{{ openstack_storage_name }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    region_name: "{{ openstack_region }}"
    availability_zone: "{{ openstack_availability_zone }}"
    volume_type: "{{ openstack_volume_type }}"
