- name: set port name, network name, ip address
  set_fact:
    port_name: "{{ list_of_ports | regex_findall('(?:([A-Za-z0-9_.]{1,}):.*)') }}"
    network_name: "{{ list_of_ports | regex_findall('(?::([A-Za-z0-9_.]{1,}):)') }}"
    ip_address: "{{ list_of_ports | regex_findall('(?::([A-Za-z0-9_.]{1,}))$') }}"

- name: create port {{ port_name.0 }}
  os_port:
    state: present
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    name: "{{ port_name.0 }}"
    network: "{{ network_name.0 }}"
    fixed_ips:
    - ip_address: "{{ ip_address.0 }}"
