- name: create storage
  os_volume:
    state: present
    size: "{{ openstack_storage_size }}"
    display_name: "{{ opestack_storage_name }}-{{ inventory_hostname }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    region_name: "{{ openstack_region }}"
    availability_zone: "{{ openstack_availability_zone }}"
