---
- name: get instance floating ip
  os_floating_ip:
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    state: present
    server: "{{ inventory_hostname }}"
    wait: True
  register: float

- name: create inventory file
  file:
    path: "{{ openstack_hosts_filename }}"
    state: touch
    mode: 0644

- name: update inventory file
  replace:
    path: "{{ openstack_hosts_filename }}"
    regexp: '^({{ inventory_hostname }}.*)'
    replace: '\1 ansible_host={{ float["floating_ip"]["floating_ip_address"] }}'
  environment:
    ANSIBLE_INVENTORY: "{{ openstack_hosts_filename }}"
