---
- import_tasks: create_instance.yml
  when: not DELETE_OS_INSTANCE

- import_tasks: delete_instance.yml
  when:  DELETE_OS_INSTANCE

- import_tasks: create_storage.yml
  when: openstack_create_storage
