---
- name: launch an instance on OpenStack
  os_server:
    state: present
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    name: "{{ hostname }}"
    region_name: "{{ region }}"
    availability_zone: "{{ availability_zone }}"
    image: "{{ image_id }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ flavor }}"
    security_groups: default
    floating_ips: "{{ floating_ip }}"
    meta: 
      hostname: "{{ hostname }}"
    nics: "{{ nic_ids }}"

- name: assign floating ip
  os_floating_ip:
    server: "{{ hostname }}"
    state: present
    network: {{ fip_network }}

- name: delete the instance on OpenStack
  os_server:
    state: absent
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    name: "{{ hostname }}"
    region_name: "{{ region }}"
    availability_zone: "{{ availability_zone }}"
  when:
    - DELETE_CFME_INSTANCE == 'True' 
